name: bin_omaira_motors
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
   # Responsive
  flutter_screenutil: ^5.9.0
  # Localization
  easy_localization: ^3.0.3
  # UI
  simple_animations: ^5.0.2
  card_swiper: ^3.0.1
  flutter_svg: ^2.0.10+1
  
  # pin_code_fields: ^8.0.1
  pinput: ^4.0.0
  country_code_picker: ^3.0.0
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: ^10.6.0
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.4
  flutter_feather_icons: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  #http
  dio: ^5.4.0
  flutter_image_compress: ^2.2.0
  url_launcher: ^6.2.5
  get_storage: ^2.1.1

  #maps
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  google_maps_place_picker_mb: ^3.1.2
  country_icons: ^3.0.0
  percent_indicator: ^4.2.3
  # custom_map_markers: ^0.0.2+1
  # #firebase
  # firebase_core: ^2.26.0
  # firebase_messaging: ^14.7.18
  # #notifications
  # flutter_ringtone_player: ^4.0.0+2
  # flutter_local_notifications: ^17.0.
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/fonts/
    - assets/lang/ar.json
    - assets/lang/en.json

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Black.otf
          weight: 900
        - asset: assets/fonts/Gotham-Bold.otf
          weight: 800
        - asset: assets/fonts/Gotham-Bold.otf
          weight: 700
        - asset: assets/fonts/Gotham-Bold.otf
          weight: 600
        - asset: assets/fonts/GothamMedium.ttf
          weight: 500
        - asset: assets/fonts/GothamBook.ttf
          weight: 500
        - asset: assets/fonts/GothamLight.ttf